### ISSUE TITLE
Is not possible to add a paragraph in the first section of the Introduction

### ISSUE THREAD

**Issue by migsorrod1** [Josdelsan/Proteus#38] opened 2024-10-22 14:44 UTC
When you try to add a new paragraph in the folder "1. Introduction", it appears in the bottom of the section. 
If you try to move up the paragraph to the section between "1. Introduction" and "1.1. Project Scope", Proteus gives an error message. We had to write the introduction of the company in the Project Scope.
![Captura de pantalla 2024-10-22 164200](https://github.com/user-attachments/assets/5cd3cfe8-09aa-4bb2-8c91-4b23ef87119c)

**Comment by Josdelsan** [comment] 2024-10-23 12:34
I could not reproduce the error locally using different projects (new project and old test projects). Looking at the provided screenshoot, I think the problem is related to where the item is being dropped. In order to illustrate the different positions where and object can be dropped, I will share some screenshots (Look how the object borders change):

- Object dropped inside another object. Object is surrounded by a box. The dropped object will be added as a child of the destination object. It will show an error message if the object is already a child of the destination object **(I think this is your case)**
![{5D23C2E7-7D29-4DD7-B111-CF079ACBF49F}](https://github.com/user-attachments/assets/9f6deff2-f2c3-457a-a588-5c37a85d2852)

- Object dropped below another object. Only bottom black border will be set. The dropped object will be included in the destination object´s parent as a child, its position will be just next to the destination object.
![{380BC83D-38C2-478C-A12F-946FF830ABE5}](https://github.com/user-attachments/assets/17221040-1cb2-4d78-ac2c-50838a7ce557)
![{6E94ABDD-E281-4FD1-B115-E2FEEC0202F1}](https://github.com/user-attachments/assets/88abecfb-c137-40f4-aa46-c10ccfc8651c)

Look how the paragraph is now in the same level as the top level sections. Now its parent is the document and not the section _1 Introduction_. This case also applies if the item is dropped above the item, just the position and border while moving will be above.

So, what you need to do in order to drop the paragraph as first child of section 1 is this scenario:
![{B197A32F-CE5D-413F-8DC6-158CDE6BA6F1}](https://github.com/user-attachments/assets/a091e0c0-f0f2-44dc-9bc9-68c40cda7199)
Look how the border is **above** section 1,1 instead of **below** section 1 (previous case). This will just move the object (paragraph) inside its parent (section 1) in order to get the first position (above section 1.1).

Another solution is using the context menu buttons to manipulate position inside parent, you will need to move it 3 times:
![{CD0DA4B4-4718-479A-9504-FC98874448A2}](https://github.com/user-attachments/assets/eedc9135-86b2-4ff5-a443-b041f687faf4)

This issue is not a bug itself but a UX/UI design flaw. It is strongly dependant on Qt framework implementation and It will be addressed in future version by increasing the size of the items in the tree or making it more obvious.

Confirm you are able to move the paragraph to the desired position so we can close the issue. In case you cannot peform the movement, share the status bar message when the paragraph is selected and when the section is selected in order to see classes conflicts.

Take note that this might be tricky if you are using a high resolution screen(4k) or high DPI mouse.

**Comment by Josdelsan** [comment] 2024-10-28 12:38
Closed due to inactivity, if the issue persist, please re-open this ticket.

**Closed as not planned by Josdelsan** 2024-10-28 12:38 UTC
Labels: wontfix
